server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
  error:
    whitelabel:
      enabled: false 
spring:
  application:
    name: enjoy-diving-service
  output:
    ansi:
      enabled: always
  profiles:
    active: dev
  http:
    encoding:
      charset: UTF-8    
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
  context-path: /application
  port: 9091
endpoints:
  sensitive: false 
  beans:
    enabled: true

---
# local
spring:
  profiles: local
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/diving
    username: sa
    password: test
    initialize: true
    schema: classpath:database/sql/ddl-*.sql
    data: classpath:database/sql/dml-*.sql

logging:
  level:
    root: DEBUG 
    org.apache: INFO
  config: classpath:config/logback-spring.xml
  file : local
  path : data/logs
  
props:
  appName: enjoy-diving-service-local
  apiVersion: v1
---  

# dev
spring:
  profiles: dev
  datasource:
    url: ENC(JhbAOrO9c0MhlBJkcBhM15vkfabBJgxc4dxv+S93sxLPAcCMCjlXIfJFEBvXMNLr)
    username: ENC(jauxnix93NIxNidJQpxZGQ==)
    password: ENC(Jbk2+ry3C3T9suJEsBqWow==)
    driver-class-name: com.mysql.jdbc.Driver
    sql-script-encoding: UTF-8
    #schema: classpath:database/sql/ddl-*.sql
    #data: classpath:database/sql/dml-*.sql
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
         
logging:
  level:
    root: DEBUG 
    org.apache: INFO
  config: classpath:config/logback-spring.xml
  file : local
  path : data/logs

props:
  appName: enjoy-diving-service-dev
  apiVersion: v1

---  

# stg
spring:
  profiles: stg
  datasource:
    url: ENC(1ahY0832tD8I5QeSK2FV4DTs33B5DUroIXrQLdq5Qlw17KviIiQUnZuc/UD4Ks7h)
    username: ENC(jauxnix93NIxNidJQpxZGQ==)
    password: ENC(Jbk2+ry3C3T9suJEsBqWow==)
    driver-class-name: com.mysql.jdbc.Driver
    sql-script-encoding: UTF-8
    #schema: classpath:database/sql/ddl-*.sql
    #data: classpath:database/sql/dml-*.sql
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      
logging:
  level:
    root: INFO 
    org.apache: INFO
  config: classpath:config/logback-spring.xml
  file : local
  path : data/logs
  
props:
  appName: enjoy-diving-service-stg
  apiVersion: v1